language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
install: npm install --save-dev
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq g++ libssl-dev 
 - npm i -g jasmine-node node-gyp


